language: objective-c
before_script:
    - brew update && brew upgrade xctool
before_install:
    - gem install cocoapods -v '0.37.1'
xcode_workspace: TwitterParam.xcworkspace
xcode_scheme: TwitterParam
xcode_sdk: iphonesimulator
