name: AppTests

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update Bundler
      run: bundle update --bundler
    - name: Install CocoaPods
      run: bundle install
    - name: Install Pods
      run: bundle exec pod install
    - name: Run tests
      run: xcodebuild clean test -workspace TwitterParam.xcworkspace -scheme TwitterParam -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Send results to codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
